
export const CONFERENCE_APPROVED_LIST_REQUEST_ADMIN = 'CONFERENCE_APPROVED_LIST_REQUEST_ADMIN'
export const CONFERENCE_APPROVED_LIST_SUCCESS_ADMIN = 'CONFERENCE_APPROVED_LIST_SUCCESS_ADMIN'
export const CONFERENCE_APPROVED_LIST_FAIL_ADMIN = 'CONFERENCE_APPROVED_LIST_FAIL_ADMIN'
export const CONFERENCE_APPROVED_LIST_RESET_ADMIN = 'CONFERENCE_APPROVED_LIST_RESET_ADMIN'


export const CONFERENCE_LIST_REQUEST_ADMIN = 'CONFERENCE_LIST_REQUEST_ADMIN'
export const CONFERENCE_LIST_SUCCESS_ADMIN = 'CONFERENCE_LIST_SUCCESS_ADMIN'
export const CONFERENCE_LIST_FAIL_ADMIN = 'CONFERENCE_LIST_FAIL_ADMIN'
export const CONFERENCE_LIST_RESET_ADMIN = 'CONFERENCE_LIST_RESET_ADMIN'

export const EDITORS_LIST_REQUEST_ADMIN = 'EDITORS_LIST_REQUEST_ADMIN'
export const EDITORS_LIST_SUCCESS_ADMIN = 'EDITORS_LIST_SUCCESS_ADMIN'
export const EDITORS_LIST_FAIL_ADMIN = 'EDITORS_LIST_FAIL_ADMIN'
export const EDITORS_LIST_RESET_ADMIN = 'EDITORS_LIST_RESET_ADMIN'

export const REVIWER_LIST_REQUEST_ADMIN = 'REVIWER_LIST_REQUEST_ADMIN'
export const REVIWER_LIST_SUCCESS_ADMIN = 'REVIWER_LIST_SUCCESS_ADMIN'
export const REVIWER_LIST_FAIL_ADMIN = 'REVIWER_LIST_FAIL_ADMIN'
export const REVIWER_LIST_RESET_ADMIN = 'REVIWER_LIST_RESET_ADMIN'

export const ADMIN_CONFERENCE_DETAILS_BYID_REQUEST = 'ADMIN_CONFERENCE_DETAILS_BYID_REQUEST'
export const ADMIN_CONFERENCE_DETAILS_BYID_SUCCESS = 'ADMIN_CONFERENCE_DETAILS_BYID_SUCCESS'
export const ADMIN_CONFERENCE_DETAILS_BYID_FAIL = 'ADMIN_CONFERENCE_DETAILS_BYID_FAIL'
export const ADMIN_CONFERENCE_DETAILS_BYID_RESET = 'ADMIN_CONFERENCE_DETAILS_BYID_RESET'