
export const CONFERENCE_APPROVED_LIST_REQUEST_ADMIN = 'CONFERENCE_APPROVED_LIST_REQUEST_ADMIN'
export const CONFERENCE_APPROVED_LIST_SUCCESS_ADMIN = 'CONFERENCE_APPROVED_LIST_SUCCESS_ADMIN'
export const CONFERENCE_APPROVED_LIST_FAIL_ADMIN = 'CONFERENCE_APPROVED_LIST_FAIL_ADMIN'
export const CONFERENCE_APPROVED_LIST_RESET_ADMIN = 'CONFERENCE_APPROVED_LIST_RESET_ADMIN'

export const CONFERENCE_LIST_REQUEST_ADMIN = 'CONFERENCE_LIST_REQUEST_ADMIN'
export const CONFERENCE_LIST_SUCCESS_ADMIN = 'CONFERENCE_LIST_SUCCESS_ADMIN'
export const CONFERENCE_LIST_FAIL_ADMIN = 'CONFERENCE_LIST_FAIL_ADMIN'
export const CONFERENCE_LIST_RESET_ADMIN = 'CONFERENCE_LIST_RESET_ADMIN'

export const EDITORS_LIST_REQUEST_ADMIN = 'EDITORS_LIST_REQUEST_ADMIN'
export const EDITORS_LIST_SUCCESS_ADMIN = 'EDITORS_LIST_SUCCESS_ADMIN'
export const EDITORS_LIST_FAIL_ADMIN = 'EDITORS_LIST_FAIL_ADMIN'
export const EDITORS_LIST_RESET_ADMIN = 'EDITORS_LIST_RESET_ADMIN'

export const REVIWER_LIST_REQUEST_ADMIN = 'REVIWER_LIST_REQUEST_ADMIN'
export const REVIWER_LIST_SUCCESS_ADMIN = 'REVIWER_LIST_SUCCESS_ADMIN'
export const REVIWER_LIST_FAIL_ADMIN = 'REVIWER_LIST_FAIL_ADMIN'
export const REVIWER_LIST_RESET_ADMIN = 'REVIWER_LIST_RESET_ADMIN'

export const ADMIN_APPROVED_REQUEST = 'ADMIN_APPROVED_REQUEST'
export const ADMIN_APPROVED_SUCCESS = 'ADMIN_APPROVED_SUCCESS'
export const ADMIN_APPROVED_FAIL = 'ADMIN_APPROVED_FAIL'
export const ADMIN_APPROVED_RESET = 'ADMIN_APPROVED_RESET'

export const ADMIN_CONFERENCE_DETAILS_ID_REQUEST = 'ADMIN_CONFERENCE_DETAILS_ID_REQUEST'
export const ADMIN_CONFERENCE_DETAILS_ID_SUCCESS = 'ADMIN_CONFERENCE_DETAILS_ID_SUCCESS'
export const ADMIN_CONFERENCE_DETAILS_ID_FAIL = 'ADMIN_CONFERENCE_DETAILS_ID_FAIL'
export const ADMIN_CONFERENCE_DETAILS_ID_RESET = 'ADMIN_CONFERENCE_DETAILS_ID_RESET'