export const CONFERENCE_LIST_REQUEST = 'CONFERENCE_LIST_REQUEST'
export const CONFERENCE_LIST_SUCCESS = 'CONFERENCE_LIST_SUCCESS'
export const CONFERENCE_LIST_FAIL = 'CONFERENCE_LIST_FAIL'
export const CONFERENCE_LIST_RESET = 'CONFERENCE_LIST_RESET'

export const CONFERENCE_APPROVED_LIST_REQUEST = 'CONFERENCE_APPROVED_LIST_REQUEST'
export const CONFERENCE_APPROVED_LIST_SUCCESS = 'CONFERENCE_APPROVED_LIST_SUCCESS'
export const CONFERENCE_APPROVED_LIST_FAIL = 'CONFERENCE_APPROVED_LIST_FAIL'
export const CONFERENCE_APPROVED_LIST_RESET = 'CONFERENCE_APPROVED_LIST_RESET'

export const CONFERENCE_UNAPPROVED_LIST_REQUEST = 'CONFERENCE_UNAPPROVED_LIST_REQUEST'
export const CONFERENCE_UNAPPROVED_LIST_SUCCESS = 'CONFERENCE_UNAPPROVED_LIST_SUCCESS'
export const CONFERENCE_UNAPPROVED_LIST_FAIL = 'CONFERENCE_UNAPPROVED_LIST_FAIL'
export const CONFERENCE_UNAPPROVED_LIST_RESET = 'CONFERENCE_UNAPPROVED_LIST_RESET'

export const CONFERENCE_DETAILS_DELETE_REQUEST = 'CONFERENCE_DETAILS_DELETE_REQUEST'
export const CONFERENCE_DETAILS_DELETE_SUCCESS = 'CONFERENCE_DETAILS_DELETE_SUCCESS'
export const CONFERENCE_DETAILS_DELETE_FAIL = 'CONFERENCE_DETAILS_DELETE_FAIL'

export const CONFERENCE_DETAILS_UPDATE_REQUEST = 'CONFERENCE_DETAILS_UPDATE_REQUEST'
export const CONFERENCE_DETAILS_UPDATE_SUCCESS = 'CONFERENCE_DETAILS_UPDATE_SUCCESS'
export const CONFERENCE_DETAILS_UPDATE_FAIL = 'CONFERENCE_DETAILS_UPDATE_FAIL'
export const CONFERENCE_DETAILS_UPDATE_RESET = 'CONFERENCE_DETAILS_UPDATE_RESET'

export const CONFERENCE_DETAILS_BYID_REQUEST = 'CONFERENCE_DETAILS_BYID_REQUEST'
export const CONFERENCE_DETAILS_BYID_SUCCESS = 'CONFERENCE_DETAILS_BYID_SUCCESS'
export const CONFERENCE_DETAILS_BYID_FAIL = 'CONFERENCE_DETAILS_BYID_FAIL'
export const CONFERENCE_DETAILS_BYID_RESET = 'CONFERENCE_DETAILS_BYID_RESET'

export const CONFERENCE_DETAILS_CREATE_REQUEST = 'CONFERENCE_DETAILS_CREATE_REQUEST'
export const CONFERENCE_DETAILS_CREATE_SUCCESS = 'CONFERENCE_DETAILS_CREATE_SUCCESS'
export const CONFERENCE_DETAILS_CREATE_FAIL = 'CONFERENCE_DETAILS_CREATE_FAIL'
export const CONFERENCE_DETAILS_CREATE_RESET = 'CONFERENCE_DETAILS_CREATE_RESET'

