export const CONFERENCE_LIST_REQUEST = 'CONFERENCE_LIST_REQUEST'
export const CONFERENCE_LIST_SUCCESS = 'CONFERENCE_LIST_SUCCESS'
export const CONFERENCE_LIST_FAIL = 'CONFERENCE_LIST_FAIL'
export const CONFERENCE_LIST_RESET = 'CONFERENCE_LIST_RESET'
