export const WORKSHOP_LIST_REQUEST_REVIWER = 'WORKSHOP_LIST_REQUEST_REVIWER'
export const WORKSHOP_LIST_SUCCESS_REVIWER = 'WORKSHOP_LIST_SUCCESS_REVIWER'
export const WORKSHOP_LIST_FAIL_REVIWER = 'WORKSHOP_LIST_FAIL_REVIWER'
export const WORKSHOP_LIST_RESET_REVIWER = 'WORKSHOP_LIST_RESET_REVIWER'