export const WORKSHOP_LIST_REQUEST_REVIWER = 'WORKSHOP_LIST_REQUEST_REVIWER'
export const WORKSHOP_LIST_SUCCESS_REVIWER = 'WORKSHOP_LIST_SUCCESS_REVIWER'
export const WORKSHOP_LIST_FAIL_REVIWER = 'WORKSHOP_LIST_FAIL_REVIWER'
export const WORKSHOP_LIST_RESET_REVIWER = 'WORKSHOP_LIST_RESET_REVIWER'

export const RESEARCH_LIST_REQUEST_REVIWER = 'RESEARCH_LIST_REQUEST_REVIWER'
export const RESEARCH_LIST_SUCCESS_REVIWER = 'RESEARCH_LIST_SUCCESS_REVIWER'
export const RESEARCH_LIST_FAIL_REVIWER = 'RESEARCH_LIST_FAIL_REVIWER'
export const RESEARCH_LIST_RESET_REVIWER = 'RESEARCH_LIST_RESET_REVIWER'